### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by ticklepoke** [anthonyfong100/CheckIT#13]
The author of this repo @anthonyfong100 is too handsome. @chinzhiweiblank

**Comment by anthonyfong100** [comment]
dafuq is this! Stop stalking me

**Comment by anthonyfong100** [comment]
pls fix this bug @ticklepoke

**Comment by chinzhiweiblank** [comment]
@anthonyfong100 @chenningg please assist. Same for @tanchuanxin @melvinfmq

**Comment by anthonyfong100** [comment]
closing this issue due to rubbish from @chinzhiweiblank

**Comment by ticklepoke** [comment]
Are you saying that you are ignoring critical bugs? Bad programming habits.

**Comment by anthonyfong100** [comment]
very humorous

**Comment by chinzhiweiblank** [comment]
@anthonyfong100 please stop stalking other people's Github. People deserve their privacy!!

**Comment by ticklepoke** [comment]
![image](https://user-images.githubusercontent.com/35065597/84133451-c7519a00-aa79-11ea-8643-7659b1f1874c.png)

**Comment by chinzhiweiblank** [comment]
@ding-si-han @ChanChiaLer @matthewljk Welcome to Anthony's crowning achievement

**Comment by anthonyfong100** [comment]
unassigned @ticklepoke and assigning to @chinzhiweiblank because @ticklepoke  seems to be not serious about this repo

**Comment by chinzhiweiblank** [comment]
Please assign me @anthonyfong100 I would like to receive notifications

**Comment by anthonyfong100** [comment]
@chinzhiweiblank please do not unassign urself. this is a serious matter

**Comment by chinzhiweiblank** [comment]
@anthonyfong100 where is my assignment?

**Comment by MelvinFMQ** [comment]
LOL

**Comment by anthonyfong100** [comment]
@chinzhiweiblank seems to be at his wits end and doesn't know how to fix it. assigning @ding-si-han in hopes of getting the issue solved
